### ISSUE TITLE
Render map (iteration 1)

### ISSUE THREAD

**Issue by SveinungOverland** [Andorr/SettlersOfCatlan#7]
To do this we need
 - [x] GameObject for game state
 - [x] Materials (basic, perhaps only colors to begin with)
 - [x] Tile prefab
 - [x] Different tiles that inherit from tile prefab and implement material
 - [x] Basic renderer (place locations, locations, locations, paths and tiles)

**Comment by Andorr** [comment]
Done! Did a basic map generation with rendering for iteration 1 in the MapPlayground scene. MapUtils generates the map, but MapController visualizes it.
